"""empty message

Revision ID: 42a5ab7f574c
Revises: d37d3680aa42
Create Date: 2018-04-25 15:13:45.963333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42a5ab7f574c'
down_revision = 'd37d3680aa42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('password_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'password_hash')
    # ### end Alembic commands ###
