"""empty message

Revision ID: 6f4431ee1250
Revises: 42a5ab7f574c
Create Date: 2018-04-25 15:17:11.848939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f4431ee1250'
down_revision = '42a5ab7f574c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('public', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'public')
    # ### end Alembic commands ###
