"""empty message

Revision ID: 412e027d098a
Revises: 2cd7402e6198
Create Date: 2018-04-24 20:53:11.905851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '412e027d098a'
down_revision = '2cd7402e6198'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roomName', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_id'), 'room', ['id'], unique=True)
    op.create_index(op.f('ix_room_roomName'), 'room', ['roomName'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('publickey', sa.String(length=256), nullable=True),
    sa.Column('room', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['room'], ['room.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.drop_index('ix_users_username', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_rooms_roomName', table_name='rooms')
    op.drop_table('rooms')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('roomName', sa.VARCHAR(length=128), nullable=False),
    sa.Column('keyset', sa.VARCHAR(length=256), nullable=True),
    sa.PrimaryKeyConstraint('roomName')
    )
    op.create_index('ix_rooms_roomName', 'rooms', ['roomName'], unique=1)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True),
    sa.Column('publickey', sa.VARCHAR(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_username', 'users', ['username'], unique=1)
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_room_roomName'), table_name='room')
    op.drop_index(op.f('ix_room_id'), table_name='room')
    op.drop_table('room')
    # ### end Alembic commands ###
